### ISSUE TITLE
The Referendum results table doesn't appear on smaller screens

### ISSUE THREAD

**Issue by catileptic** [code4romania/rezultate-vot-client#68] opened 2020-09-27 09:57 UTC
The table doesn't appear on smaller screens (13 inch here - also reproduces on mobile).
![image](https://user-images.githubusercontent.com/14028425/94361990-e45db780-00c0-11eb-806e-2f5619bdf300.png)

**Comment by dapetcu21** [comment] 2020-10-02 14:30
This is not a bug. It's implemented according to the design. There is no space for that summary table and no point showing the table again when, immediately scrolling down, you get the same data in a slightly differently styled table.

**Comment by Utwo** [comment] 2020-10-04 19:04
Thank you, will close this ;)

**Closed by Utwo** 2020-10-04 19:04 UTC
Labels: bug, frontend
